[package]
name = "hub-william-backend"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
axum = "0.8.9"
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.53.1", features = ["macros", "net", "rt-multi-thread", "signal"] }
utoipa = { version = "5.5.0", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "9.0.2", features = ["axum", "vendored"] }

[dev-dependencies]
serde_json = "1.0.149"
tower = { version = "0.5.3", features = ["util"] }
