import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";

import PlaygroundResponse from "./playground-response";

describe("Playground assistant responses", () => {
  it("renders completed Markdown including GFM without activating raw HTML", () => {
    render(
      <PlaygroundResponse
        streaming={false}
        text={
          "# Summary\n\n**Ready** with `code`.\n\n- First\n- Second\n\n| Model | Status |\n| --- | --- |\n| One | Done |\n\n<script>window.evil = true</script>"
        }
      />,
    );

    expect(screen.getByRole("heading", { name: "Summary" })).toBeVisible();
    expect(screen.getByText("Ready", { selector: "strong" })).toBeVisible();
    expect(screen.getByText("code", { selector: "code" })).toBeVisible();
    expect(screen.getByRole("list").children).toHaveLength(2);
    expect(screen.getByRole("table")).toBeVisible();
    expect(document.querySelector("script")).toBeNull();
  });

  it("previews fenced SVG as a sanitized image and keeps its source available", () => {
    render(
      <PlaygroundResponse
        streaming={false}
        text={
          'Here is the icon:\n\n```svg\n<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 40 40" onload="alert(1)"><script>alert(1)</script><foreignObject><body onload="alert(1)">unsafe</body></foreignObject><rect width="40" height="40" fill="red"/></svg>\n```'
        }
      />,
    );

    const preview = screen.getByRole("img", {
      name: "SVG generated by the model",
    });
    const imageSource = preview.getAttribute("src") ?? "";
    expect(imageSource).toMatch(/^data:image\/svg\+xml/);
    const svg = decodeURIComponent(imageSource.split(",")[1]);
    expect(svg).toContain("<rect");
    expect(svg).not.toMatch(/<script|onload=|foreignObject|<body/i);
    expect(document.querySelector("svg")).toBeNull();
    expect(screen.getByText("View SVG source")).toBeVisible();
  });

  it("previews raw SVG between prose and leaves remote Markdown images inert", () => {
    const { rerender } = render(
      <PlaygroundResponse
        streaming={false}
        text={
          'Here is the icon:\n\n<svg viewBox="0 0 10 10"><circle r="4" cx="5" cy="5"/></svg>\n\nReady to use.'
        }
      />,
    );
    expect(screen.getByText("Here is the icon:")).toBeVisible();
    expect(
      screen.getByRole("img", { name: "SVG generated by the model" }),
    ).toBeVisible();
    expect(screen.getByText("Ready to use.")).toBeVisible();

    rerender(
      <PlaygroundResponse
        streaming={false}
        text="![remote preview](https://example.com/image.png)"
      />,
    );
    expect(screen.queryByRole("img")).not.toBeInTheDocument();
    expect(screen.getByText("[Image: remote preview]")).toBeVisible();
  });

  it("previews every raw SVG after an unrelated code block", () => {
    render(
      <PlaygroundResponse
        streaming={false}
        text={
          '```js\nconst example = 1;\n```\n\n<svg viewBox="0 0 10 10"><circle r="4" cx="5" cy="5"/></svg>\n\n<svg viewBox="0 0 10 10"><rect width="10" height="10"/></svg>'
        }
      />,
    );

    expect(
      screen.getByText("const example = 1;", { selector: "code" }),
    ).toBeVisible();
    expect(
      screen.getAllByRole("img", { name: "SVG generated by the model" }),
    ).toHaveLength(2);
  });

  it("previews a raw SVG that contains a nested SVG element", () => {
    render(
      <PlaygroundResponse
        streaming={false}
        text={
          '<svg viewBox="0 0 20 20"><svg x="5" y="5"><circle r="2"/></svg></svg>'
        }
      />,
    );

    const source = screen
      .getByRole("img", { name: "SVG generated by the model" })
      .getAttribute("src");
    expect(source).toContain("%3Csvg");
    expect(decodeURIComponent(source?.split(",")[1] ?? "")).toContain(
      "<circle",
    );
  });

  it("keeps partial streaming output as text until it completes", () => {
    render(<PlaygroundResponse streaming text="# Still streaming" />);
    expect(screen.queryByRole("heading")).not.toBeInTheDocument();
    expect(screen.getByText("# Still streaming")).toBeVisible();
  });
});
