import { Children, isValidElement, type ReactNode } from "react";
import DOMPurify from "dompurify";
import Markdown, { type Components } from "react-markdown";
import remarkGfm from "remark-gfm";

import ImageFallBack from "@/components/ui/image-fallback";

interface PlaygroundResponseProps {
  streaming: boolean;
  text: string;
}

interface PlaygroundSvgPreviewProps {
  source: string;
}

interface PlaygroundMarkdownBodyProps {
  text: string;
}

interface PlaygroundResponsePart {
  kind: "markdown" | "svg";
  text: string;
}

interface PlaygroundCodeElementProps {
  children?: ReactNode;
  className?: string;
}

interface PlaygroundFence {
  character: string;
  length: number;
}

const SVG_NAMESPACE = "http://www.w3.org/2000/svg";
const MAX_SVG_LENGTH = 256 * 1024;

function svgImageSource(source: string) {
  const trimmed = source.trim();
  if (trimmed.length > MAX_SVG_LENGTH || !/^<svg(?:\s|>)/i.test(trimmed))
    return null;

  const sanitized = DOMPurify.sanitize(trimmed, {
    USE_PROFILES: { svg: true, svgFilters: true },
    FORBID_TAGS: [
      "a",
      "animate",
      "animateMotion",
      "animateTransform",
      "foreignObject",
      "image",
      "script",
      "set",
      "style",
    ],
    FORBID_ATTR: ["href", "style", "xlink:href"],
  });
  const document = new DOMParser().parseFromString(sanitized, "image/svg+xml");
  if (
    document.querySelector("parsererror") ||
    document.documentElement.localName !== "svg"
  )
    return null;

  document.documentElement.setAttribute("xmlns", SVG_NAMESPACE);
  const safeSvg = new XMLSerializer().serializeToString(
    document.documentElement,
  );
  return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(safeSvg)}`;
}

function PlaygroundSvgPreview({ source }: PlaygroundSvgPreviewProps) {
  const imageSource = svgImageSource(source);
  if (!imageSource)
    return (
      <pre className="overflow-x-auto rounded-lg bg-zinc-950 p-4 text-xs text-zinc-50">
        <code>{source}</code>
      </pre>
    );

  return (
    <figure className="not-prose space-y-3 rounded-lg border border-border bg-white p-3">
      <ImageFallBack
        src={imageSource}
        alt="SVG generated by the model"
        fallback="SVG preview unavailable"
        className="max-h-96 w-full object-contain"
      />

      <details className="text-xs text-muted-foreground">
        <summary className="cursor-pointer">View SVG source</summary>

        <pre className="mt-2 max-h-64 overflow-auto rounded-lg bg-zinc-950 p-3 text-zinc-50">
          <code>{source}</code>
        </pre>
      </details>
    </figure>
  );
}

const components: Components = {
  a({ children, href }) {
    return (
      <a href={href} target="_blank" rel="noopener noreferrer">
        {children}
      </a>
    );
  },
  img({ alt }) {
    return <span>{alt ? `[Image: ${alt}]` : "[Image]"}</span>;
  },
  pre({ children }) {
    const code = Children.toArray(children)[0];
    if (
      isValidElement<PlaygroundCodeElementProps>(code) &&
      typeof code.props.children === "string" &&
      /^<svg(?:\s|>)/i.test(code.props.children.trim())
    )
      return <PlaygroundSvgPreview source={code.props.children} />;
    return <pre>{children}</pre>;
  },
};

function PlaygroundMarkdownBody({ text }: PlaygroundMarkdownBodyProps) {
  if (!text.trim()) return null;
  return (
    <div className="prose prose-sm max-w-none wrap-anywhere prose-a:text-indigo-600 prose-pre:overflow-x-auto">
      <Markdown remarkPlugins={[remarkGfm]} components={components}>
        {text}
      </Markdown>
    </div>
  );
}

function insideFencedCode(text: string, offset: number) {
  let open: PlaygroundFence | null = null;
  for (const line of text.slice(0, offset).split("\n")) {
    const fence = /^ {0,3}(`{3,}|~{3,})(.*)$/.exec(line);
    if (!fence) continue;
    const marker = fence[1];
    if (!open) {
      open = { character: marker[0], length: marker.length };
    } else if (
      marker[0] === open.character &&
      marker.length >= open.length &&
      !fence[2].trim()
    ) {
      open = null;
    }
  }
  return open !== null;
}

function rawSvgEnd(text: string, start: number) {
  const lowerText = text.toLowerCase();
  let close = lowerText.indexOf("</svg>", start);
  while (close !== -1 && close + "</svg>".length - start <= MAX_SVG_LENGTH) {
    const end = close + "</svg>".length;
    const document = new DOMParser().parseFromString(
      text.slice(start, end),
      "image/svg+xml",
    );
    if (
      !document.querySelector("parsererror") &&
      document.documentElement.localName === "svg"
    )
      return end;
    close = lowerText.indexOf("</svg>", end);
  }
  return null;
}

function splitRawSvg(text: string): PlaygroundResponsePart[] {
  const parts: PlaygroundResponsePart[] = [];
  const pattern = /(^|\n) {0,3}<svg(?:\s|>)/gim;
  let cursor = 0;
  let match: RegExpExecArray | null;
  while ((match = pattern.exec(text))) {
    const start = match.index + match[0].toLowerCase().indexOf("<svg");
    if (insideFencedCode(text, start)) continue;
    const end = rawSvgEnd(text, start);
    if (end === null) continue;
    if (start > cursor)
      parts.push({ kind: "markdown", text: text.slice(cursor, start) });
    parts.push({ kind: "svg", text: text.slice(start, end) });
    cursor = end;
    pattern.lastIndex = end;
  }
  if (cursor < text.length)
    parts.push({ kind: "markdown", text: text.slice(cursor) });
  return parts;
}

export default function PlaygroundResponse({
  streaming,
  text,
}: PlaygroundResponseProps) {
  if (streaming)
    return (
      <p className="text-sm/relaxed whitespace-pre-wrap wrap-anywhere">
        {text}
      </p>
    );

  const parts = splitRawSvg(text);
  if (parts.length === 1 && parts[0].kind === "markdown")
    return <PlaygroundMarkdownBody text={text} />;

  return (
    <div className="space-y-3">
      {parts.map((part, index) =>
        part.kind === "svg" ? (
          <PlaygroundSvgPreview key={index} source={part.text} />
        ) : (
          <PlaygroundMarkdownBody key={index} text={part.text} />
        ),
      )}
    </div>
  );
}
