// Generated by scripts/provider-catalogue.py. Edit provider_catalogue.json.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, PartialEq, Serialize, ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum AgentProvider {
    #[serde(rename = "chatgpt")]
    Chatgpt,
    #[serde(rename = "claude")]
    Claude,
    #[serde(rename = "gemini")]
    Gemini,
    #[serde(rename = "grok")]
    Grok,
    #[serde(rename = "deepseek")]
    Deepseek,
    #[serde(rename = "groq")]
    Groq,
}
impl AgentProvider {
    pub(crate) const ALL: [Self; 6] = [
        Self::Chatgpt,
        Self::Claude,
        Self::Gemini,
        Self::Grok,
        Self::Deepseek,
        Self::Groq,
    ];
    pub(crate) fn as_str(self) -> &'static str {
        match self {
            Self::Chatgpt => "chatgpt",
            Self::Claude => "claude",
            Self::Gemini => "gemini",
            Self::Grok => "grok",
            Self::Deepseek => "deepseek",
            Self::Groq => "groq",
        }
    }
}

pub(crate) const CALL_CODEX_REALTIME_MODEL: &str = "gpt-live-1-codex";
pub(crate) const CALL_GROQ_CHAT_MODEL: &str = "openai/gpt-oss-20b";
pub(crate) const CALL_GROQ_TTS_MODEL: &str = "canopylabs/orpheus-v1-english";
