/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/agent-connections": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_connections"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/agent-connections/deepseek": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["connect_deepseek"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/agent-connections/groq": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["connect_groq"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/agent-connections/start": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["start"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/agent-connections/{connection_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_connection"];
    put?: never;
    post?: never;
    delete: operations["disconnect"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/agent-connections/{connection_id}/complete": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["complete_authorization"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/agent-connections/{connection_id}/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["refresh_connection"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/agent-pool-requests/{request_id}/decision": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["decide_request"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/agent-pools": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/agent-pools/{connection_id}/members": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["invite_member"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/agent-pools/{connection_id}/members/{username}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["remove_member"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/agent-pools/{connection_id}/requests": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["create_request"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["refresh"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["register"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/session": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["session"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/gateway-keys": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_keys"];
    put?: never;
    post: operations["create_key"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/gateway-keys/{key_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["revoke_key"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["health"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/organization-invitations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_invitations"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/organization-invitations/{invitation_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["decline_invitation"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/organization-invitations/{invitation_id}/accept": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["accept_invitation"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/organization-summaries": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * The My organizations table: every organization the viewer belongs to with its
     *     owner, agent and member counts and its recorded usage. Aggregating the usage
     *     costs more than the plain list, so only that table asks for it.
     */
    get: operations["list_organization_summaries"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/organizations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_organizations"];
    put?: never;
    post: operations["create_organization"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/organizations/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete an organization as its owner. Every member leaves with it and its
     *     invitations, shared-agent links and recorded usage are removed. The
     *     Workspace connections behind the shared agents are not touched.
     */
    delete: operations["delete_organization"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/organizations/{id}/agents": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_agents"];
    put?: never;
    /**
     * Link an owned Workspace connection into an organization. The organization
     *     agent is the same connection and credential, not a copy. Repeating the
     *     request, including concurrently, returns the existing link.
     */
    post: operations["share_agent"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/organizations/{id}/agents/{connection_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["unshare_agent"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/organizations/{id}/default": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Make an organization the viewer's default, the one their Organization pages
     *     open with. Only an accepted member can, and the previous default stops being
     *     one. Repeating the request changes nothing.
     */
    put: operations["set_default_organization"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/organizations/{id}/members": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_members"];
    put?: never;
    post: operations["organization_invite_member"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/organizations/{id}/members/{username}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["organization_remove_member"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/organizations/{id}/membership": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Leave an organization as one of its accepted members. Agents the member
     *     shared are unlinked from it; their Workspace connections stay connected.
     *     The owner cannot leave and deletes the organization instead.
     */
    delete: operations["leave_organization"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/organizations/{id}/overview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["overview"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/organizations/{id}/usage": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["usage"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/playground/chat": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["chat"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/playground/groq/voice/turn": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["create_groq_voice_turn"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/playground/voice": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/playground/{provider}/accounts/{connection_id}/models": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["models"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AgentAuthorizationPrompt: {
      authorization_url: string;
      /** Format: date-time */
      expires_at: string;
      /** Format: int64 */
      poll_after_seconds: number;
      requires_callback_url: boolean;
      user_code?: string | null;
    };
    AgentConnection: {
      account_label?: string | null;
      authorization?: null | components["schemas"]["AgentAuthorizationPrompt"];
      availability_status: string;
      /** Format: date-time */
      created_at: string;
      failure_message?: string | null;
      /** Format: uuid */
      id: string;
      plan?: string | null;
      provider: components["schemas"]["AgentProvider"];
      status: components["schemas"]["AgentConnectionStatus"];
      /** Format: date-time */
      updated_at: string;
    };
    /** @enum {string} */
    AgentConnectionStatus: "pending" | "connected" | "failed" | "disconnected";
    AgentPool: {
      account_label: string;
      agent: string;
      availability: components["schemas"]["AgentPoolAvailability"];
      /** Format: int32 */
      capacity: number;
      /** Format: date-time */
      created_at: string;
      /** Format: uuid */
      id: string;
      members: components["schemas"]["AgentPoolPerson"][];
      owner: components["schemas"]["AgentPoolPerson"];
      plan: string;
      requests: components["schemas"]["AgentPoolJoinRequest"][];
      usage: components["schemas"]["AgentPoolUsageMetric"][];
    };
    AgentPoolAvailability: {
      /** Format: date-time */
      retry_at?: string | null;
      status: components["schemas"]["AgentPoolAvailabilityStatus"];
    };
    /** @enum {string} */
    AgentPoolAvailabilityStatus:
      "active" | "rate_limited" | "half_open" | "reauth_required";
    AgentPoolJoinRequest: {
      avatar_label: string;
      /** Format: uuid */
      id: string;
      reason: string;
      status: components["schemas"]["AgentPoolRequestStatus"];
      telegram: string;
      username: string;
    };
    AgentPoolPerson: {
      avatar_label: string;
      /** Format: date-time */
      joined_at: string;
      share: components["schemas"]["AgentPoolShareEvidence"];
      /** Format: int32 */
      usage_available_percent: number;
      username: string;
    };
    /** @enum {string} */
    AgentPoolRequestStatus: "pending" | "accepted" | "rejected";
    AgentPoolShareEvidence: {
      /** Format: int32 */
      available_percent: number;
      /** Format: int64 */
      budget_units?: number | null;
      /** Format: int64 */
      cap_units?: number | null;
      fail_open_reason?: string | null;
      /** Format: int32 */
      member_count: number;
      /** Format: int64 */
      pool_cached_tokens: number;
      /** Format: int64 */
      pool_input_tokens: number;
      /** Format: int64 */
      pool_output_tokens: number;
      /** Format: int64 */
      pool_units: number;
      /** Format: double */
      provider_used_percent?: number | null;
      /** Format: int64 */
      remaining_units?: number | null;
      /** Format: int64 */
      user_cached_tokens: number;
      /** Format: int64 */
      user_input_tokens: number;
      /** Format: int64 */
      user_output_tokens: number;
      /** Format: int64 */
      user_units: number;
      window_label?: string | null;
    };
    AgentPoolUsageMetric: {
      detail?: string | null;
      label: string;
      value: string;
    };
    /** @enum {string} */
    AgentProvider:
      "chatgpt" | "claude" | "gemini" | "grok" | "deepseek" | "groq";
    AuthenticatedUser: {
      /** Format: uuid */
      id: string;
      recovery_email?: string | null;
      username: string;
    };
    /** @enum {string} */
    CallKind: "native_realtime" | "local_stt_llm_tts";
    CallProfile: {
      availability: string;
      id: string;
      kind: components["schemas"]["CallKind"];
      models: {
        [key: string]: string;
      };
      name: string;
      provider: components["schemas"]["AgentProvider"];
      selector_model: string;
      transport: components["schemas"]["CallTransport"];
    };
    /** @enum {string} */
    CallTransport: "codex_v3_webrtc" | "groq_sse";
    CompleteAuthorizationRequest: {
      callback_url: string;
    };
    ConnectDeepseekRequest: {
      api_key: string;
    };
    ConnectGroqRequest: {
      api_key: string;
    };
    CreateAgentPoolJoinRequest: {
      reason: string;
      telegram: string;
    };
    CreateOrganization: {
      description?: string | null;
      name: string;
    };
    CreatedGatewayKey: components["schemas"]["GatewayKey"] & {
      key: string;
    };
    DecideAgentPoolJoinRequest: {
      status: components["schemas"]["AgentPoolRequestStatus"];
    };
    ErrorResponse: {
      code: string;
      message: string;
    };
    GatewayKey: {
      /** Format: date-time */
      created_at: string;
      /** Format: uuid */
      id: string;
      last_four: string;
      /** Format: date-time */
      last_used_at?: string | null;
    };
    GroqVoiceMessage: {
      content: string;
      role: components["schemas"]["PlaygroundRole"];
    };
    GroqVoiceTurnRequest: {
      /** Format: uuid */
      connection_id: string;
      messages: components["schemas"]["GroqVoiceMessage"][];
      model: string;
      /** Format: uuid */
      organization_id?: string | null;
      /** @description Stream accepted transcript, reply deltas and audio clips as SSE. */
      stream?: boolean;
      /** @description With stream=true, allow sentence audio to interleave with reply deltas. */
      stream_audio?: boolean;
      /** @description Final transcript recognized locally in the browser, at most 8000 UTF-8 bytes. */
      transcript: string;
    };
    GroqVoiceTurnResponse: {
      /** @description Ordered base64 WAV clips. Each TTS input is at most 200 characters. */
      audio: string[];
      reply: string;
      transcript: string;
    };
    HealthResponse: {
      service: string;
      status: string;
    };
    InviteAgentPoolMember: {
      username: string;
    };
    InviteOrganizationMember: {
      username: string;
    };
    LoginRequest: {
      password: string;
      username: string;
    };
    /** @enum {string} */
    ModelCapability:
      | "chat"
      | "image_input"
      | "realtime_audio"
      | "transcription"
      | "speech_output";
    Organization: {
      /** Format: date-time */
      created_at: string;
      description?: string | null;
      /** Format: uuid */
      id: string;
      /**
       * @description The organization the viewer's Organization pages open with. At most one
       *     organization is the default; creating or joining one, or choosing it,
       *     makes it the default, and leaving it or its deletion clears that.
       */
      is_default: boolean;
      name: string;
      role: string;
    };
    OrganizationAgent: {
      account_label?: string | null;
      availability_status: string;
      /** Format: date-time */
      created_at: string;
      /** Format: uuid */
      id: string;
      owner_username: string;
      provider: string;
      /** Format: date-time */
      rate_limited_until?: string | null;
    };
    OrganizationAgentDetails: {
      account_label?: string | null;
      availability_status: string;
      /** Format: date-time */
      created_at: string;
      /** Format: uuid */
      id: string;
      owner_username: string;
      plan: string;
      provider: string;
      /** Format: date-time */
      rate_limited_until?: string | null;
      usage: components["schemas"]["AgentPoolUsageMetric"][];
    };
    OrganizationAgentListQuery: {
      include_usage?: boolean | null;
    };
    OrganizationInvitation: {
      /** Format: date-time */
      created_at: string;
      /** Format: uuid */
      id: string;
      invited_by_username?: string | null;
      /** Format: uuid */
      organization_id: string;
      organization_name: string;
    };
    OrganizationMember: {
      /**
       * Format: uuid
       * @description The Hub user ID, also used by the Usage member_id filter.
       */
      id: string;
      /** Format: date-time */
      invited_at: string;
      invited_by_username?: string | null;
      /** Format: date-time */
      joined_at?: string | null;
      role: string;
      status: string;
      username: string;
    };
    OrganizationOverview: {
      /** Format: int64 */
      agent_count: number;
      agents: components["schemas"]["OrganizationAgent"][];
      daily_usage: components["schemas"]["OrganizationUsageDay"][];
      /** Format: int64 */
      known_cached_tokens: number;
      /** Format: int64 */
      known_input_tokens: number;
      /** Format: int64 */
      known_output_tokens: number;
      /** Format: int64 */
      member_count: number;
      organization: components["schemas"]["Organization"];
      /** Format: int64 */
      period_days: number;
      /** Format: int64 */
      requests: number;
      /** Format: int64 */
      token_known_requests: number;
    };
    OrganizationPeriodQuery: {
      /** Format: int64 */
      days?: number | null;
    };
    /**
     * @description An organization the viewer belongs to, with what the My organizations table
     *     shows: the owner, the agent and member counts, and recorded usage over the
     *     last `period_days` UTC days (the same figures its Overview reports).
     */
    OrganizationSummary: {
      /** Format: int64 */
      agent_count: number;
      /** Format: date-time */
      created_at: string;
      description?: string | null;
      /** Format: uuid */
      id: string;
      /** @description Whether this is the organization the viewer's Organization pages open with. */
      is_default: boolean;
      /** Format: int64 */
      known_cached_tokens: number;
      /** Format: int64 */
      known_input_tokens: number;
      /** Format: int64 */
      known_output_tokens: number;
      /** Format: int64 */
      member_count: number;
      name: string;
      owner_username: string;
      /** Format: int64 */
      period_days: number;
      /** Format: int64 */
      requests: number;
      role: string;
      /** Format: int64 */
      token_known_requests: number;
    };
    OrganizationUsage: {
      breakdown: components["schemas"]["OrganizationUsageBreakdown"][];
      daily_usage: components["schemas"]["OrganizationUsageDay"][];
      /** Format: int64 */
      known_cached_tokens: number;
      /** Format: int64 */
      known_input_tokens: number;
      /** Format: int64 */
      known_output_tokens: number;
      /** Format: int64 */
      period_days: number;
      /** Format: int64 */
      requests: number;
      /** Format: int64 */
      token_known_requests: number;
    };
    OrganizationUsageBreakdown: {
      /** Format: uuid */
      connection_id?: string | null;
      /** Format: int64 */
      known_cached_tokens: number;
      /** Format: int64 */
      known_input_tokens: number;
      /** Format: int64 */
      known_output_tokens: number;
      /** Format: uuid */
      member_id: string;
      model?: string | null;
      provider: string;
      /** Format: int64 */
      requests: number;
      /** Format: int64 */
      token_known_requests: number;
      username: string;
    };
    OrganizationUsageDay: {
      date: string;
      /** Format: int64 */
      known_total_tokens: number;
      /** Format: int64 */
      requests: number;
      /** Format: int64 */
      token_known_requests: number;
    };
    OrganizationUsageQuery: {
      /** Format: uuid */
      connection_id?: string | null;
      /** Format: int64 */
      days?: number | null;
      /** Format: uuid */
      member_id?: string | null;
      model?: string | null;
    };
    PlaygroundAttachment:
      | {
          data: string;
          /** @enum {string} */
          kind: "image";
          media_type: string;
          name: string;
        }
      | {
          /** @enum {string} */
          kind: "text";
          name: string;
          text: string;
        };
    PlaygroundChatRequest: {
      /** Format: uuid */
      connection_id: string;
      messages: components["schemas"]["PlaygroundMessage"][];
      model: string;
      /** Format: uuid */
      organization_id?: string | null;
      provider: components["schemas"]["AgentProvider"];
    };
    PlaygroundMessage: {
      attachments?: components["schemas"]["PlaygroundAttachment"][];
      content: string;
      role: components["schemas"]["PlaygroundRole"];
    };
    /** @enum {string} */
    PlaygroundMode: "chat" | "voice";
    PlaygroundModel: {
      call?: null | components["schemas"]["CallProfile"];
      capabilities: components["schemas"]["ModelCapability"][];
      id: string;
      modes: components["schemas"]["PlaygroundMode"][];
      name: string;
    };
    /** @enum {string} */
    PlaygroundRole: "user" | "assistant";
    PlaygroundVoiceRequest: {
      /** Format: uuid */
      connection_id: string;
      model: string;
      /** Format: uuid */
      organization_id?: string | null;
      provider: components["schemas"]["AgentProvider"];
      sdp: string;
    };
    PlaygroundVoiceSession: {
      sdp: string;
    };
    RegisterRequest: {
      password: string;
      recovery_email?: string | null;
      username: string;
    };
    SessionResponse: {
      user: components["schemas"]["AuthenticatedUser"];
    };
    ShareOrganizationAgent: {
      /** Format: uuid */
      connection_id: string;
    };
    StartAgentConnectionRequest: {
      provider: components["schemas"]["AgentProvider"];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  list_connections: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current user's provider connections */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AgentConnection"][];
        };
      };
      /** @description Hub login required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  connect_deepseek: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConnectDeepseekRequest"];
      };
    };
    responses: {
      /** @description DeepSeek API key validated and encrypted */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AgentConnection"];
        };
      };
      /** @description Hub login required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Invalid DeepSeek API key */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description DeepSeek validation unavailable */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  connect_groq: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConnectGroqRequest"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AgentConnection"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  start: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StartAgentConnectionRequest"];
      };
    };
    responses: {
      /** @description Provider authorization started */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AgentConnection"];
        };
      };
      /** @description Hub login required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Provider authorization unavailable */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_connection: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Agent connection ID */
        connection_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Latest provider connection status */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AgentConnection"];
        };
      };
      /** @description Connection not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  disconnect: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Agent connection ID */
        connection_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Connected account pool deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Connection not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  complete_authorization: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Agent connection ID */
        connection_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CompleteAuthorizationRequest"];
      };
    };
    responses: {
      /** @description Authorization completed */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AgentConnection"];
        };
      };
      /** @description Invalid callback URL */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Provider rejected the exchange */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  refresh_connection: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Agent connection ID */
        connection_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Credential refreshed or provider reauthorization started */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AgentConnection"];
        };
      };
      /** @description Hub login required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Connection not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Provider refresh unavailable */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  decide_request: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Join request identifier */
        request_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DecideAgentPoolJoinRequest"];
      };
    };
    responses: {
      /** @description Join request decided */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AgentPoolJoinRequest"];
        };
      };
      /** @description Pool ownership required */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Connected account pools */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AgentPool"][];
        };
      };
    };
  };
  invite_member: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Connected account identifier */
        connection_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["InviteAgentPoolMember"];
      };
    };
    responses: {
      /** @description Member invited */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AgentPoolPerson"];
        };
      };
      /** @description Pool ownership required */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Invite rejected */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  remove_member: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Connected account identifier */
        connection_id: string;
        /** @description Hub William username */
        username: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Member removed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Pool ownership required */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Membership not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  create_request: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Connected account identifier */
        connection_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateAgentPoolJoinRequest"];
      };
    };
    responses: {
      /** @description Join request created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AgentPoolJoinRequest"];
        };
      };
      /** @description Login required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Request rejected */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Session started */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionResponse"];
        };
      };
      /** @description Credentials rejected */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Invalid account fields */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Session ended */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  refresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Access and refresh sessions rotated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionResponse"];
        };
      };
      /** @description Refresh session missing or expired */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  register: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterRequest"];
      };
    };
    responses: {
      /** @description Account created and session started */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionResponse"];
        };
      };
      /** @description Username already exists */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Invalid account fields */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  session: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current authenticated user */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionResponse"];
        };
      };
      /** @description No browser session has been started */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No active session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  list_keys: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Active gateway keys */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GatewayKey"][];
        };
      };
      /** @description Hub login required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  create_key: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Gateway key created and returned once */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreatedGatewayKey"];
        };
      };
      /** @description Hub login required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Connected provider not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  revoke_key: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Gateway key ID */
        key_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Gateway key revoked */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Gateway key not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Backend is ready to accept requests */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  list_invitations: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Viewer's pending organization invitations */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrganizationInvitation"][];
        };
      };
    };
  };
  decline_invitation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Pending membership ID */
        invitation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Invitation declined */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  accept_invitation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Pending membership ID */
        invitation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Invitation accepted and the organization made the member's default */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Organization"];
        };
      };
    };
  };
  list_organization_summaries: {
    parameters: {
      query?: {
        /** @description UTC calendar days of usage to summarize, 1 through 365; defaults to 30 */
        days?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Organizations where the viewer is an accepted member, with their owner, counts and recent usage */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrganizationSummary"][];
        };
      };
    };
  };
  list_organizations: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Organizations where the viewer is an accepted member */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Organization"][];
        };
      };
    };
  };
  create_organization: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateOrganization"];
      };
    };
    responses: {
      /** @description Organization created and made the creator's default */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Organization"];
        };
      };
    };
  };
  delete_organization: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Organization ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Organization deleted with its memberships, invitations, agent links and recorded usage */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  list_agents: {
    parameters: {
      query?: {
        /** @description Fetch live provider quota metrics; defaults to false */
        include_usage?: boolean;
      };
      header?: never;
      path: {
        /** @description Organization ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Shared connected agents and provider usage */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrganizationAgentDetails"][];
        };
      };
    };
  };
  share_agent: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Organization ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ShareOrganizationAgent"];
      };
    };
    responses: {
      /** @description Owned agent was already linked; the existing link is returned */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrganizationAgent"];
        };
      };
      /** @description Owned agent linked to the organization */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrganizationAgent"];
        };
      };
    };
  };
  unshare_agent: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Organization ID */
        id: string;
        /** @description Owned connection ID */
        connection_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Agent unshared */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  set_default_organization: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Organization ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The organization is now the viewer's default */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  list_members: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Organization ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Accepted and pending organization members */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrganizationMember"][];
        };
      };
    };
  };
  organization_invite_member: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Organization ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["InviteOrganizationMember"];
      };
    };
    responses: {
      /** @description Existing Hub user invited */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrganizationMember"];
        };
      };
    };
  };
  organization_remove_member: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Organization ID */
        id: string;
        /** @description Hub username */
        username: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Member removed or invitation canceled */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  leave_organization: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Organization ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The viewer left the organization */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  overview: {
    parameters: {
      query?: {
        /** @description UTC calendar days, 1 through 365; defaults to 30 */
        days?: number;
      };
      header?: never;
      path: {
        /** @description Organization ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Organization overview */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrganizationOverview"];
        };
      };
    };
  };
  usage: {
    parameters: {
      query?: {
        /** @description UTC calendar days, 1 through 365; defaults to 30 */
        days?: number;
        /** @description Hub user ID */
        member_id?: string;
        /** @description Shared connection ID */
        connection_id?: string;
        /** @description Exact upstream model ID */
        model?: string;
      };
      header?: never;
      path: {
        /** @description Organization ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Organization usage recorded by accepted upstream requests */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrganizationUsage"];
        };
      };
    };
  };
  chat: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PlaygroundChatRequest"];
      };
    };
    responses: {
      /** @description Provider-native text event stream */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/event-stream": string;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  create_groq_voice_turn: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GroqVoiceTurnRequest"];
      };
    };
    responses: {
      /** @description JSON by default; stream=true returns SSE transcript, delta, audio, done or error events. stream_audio=true allows delta and audio to interleave */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GroqVoiceTurnResponse"];
          "text/event-stream": string;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PlaygroundVoiceRequest"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PlaygroundVoiceSession"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  models: {
    parameters: {
      query?: {
        /** @description Organization whose shared agent should be used */
        organization_id?: string;
      };
      header?: never;
      path: {
        provider: components["schemas"]["AgentProvider"];
        connection_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PlaygroundModel"][];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
}
