-- Claude Code reports usage by pushing OpenTelemetry to the hub, not by being
-- polled like Codex. That inverts two assumptions the Codex tables were built
-- on, and both are handled here rather than in the Edge Function:
--
--   1. Telemetry arrives as deltas. A plain upsert would overwrite a bucket
--      with the newest request instead of adding to it, so every write below
--      goes through a function that increments.
--   2. Events for one prompt arrive out of order and span several models
--      (main turn, tool turns, subagents). Attributing a prompt to whichever
--      model burnt the most tokens keeps per-model prompt counts a partition:
--      they sum to the prompt total instead of double counting.

-- One row per user prompt. Content is optional: a project that never sets
-- OTEL_LOG_USER_PROMPTS still produces rows, just with a null excerpt, so
-- prompt counts work for repositories whose text is deliberately not collected.
create table public.prompt_events (
  id bigint generated by default as identity primary key,
  connection_id uuid not null references public.provider_connections (id) on delete cascade,
  prompt_id text not null,
  session_id text,
  occurred_at timestamptz not null,
  -- Dominant model, recomputed on every attribution. 'unknown' until the first
  -- api_request for this prompt lands.
  model text not null default 'unknown',
  model_tokens jsonb not null default '{}'::jsonb,
  excerpt text,
  prompt_length integer not null default 0 check (prompt_length >= 0),
  command_name text,
  command_source text,
  observed_at timestamptz not null default now(),
  check (jsonb_typeof(model_tokens) = 'object')
);

-- Telemetry retries deliveries, so the same prompt can arrive more than once.
create unique index prompt_events_prompt_unique
on public.prompt_events (connection_id, prompt_id);

create index prompt_events_connection_model_idx
on public.prompt_events (connection_id, model, occurred_at desc);

alter table public.prompt_events enable row level security;
revoke all on table public.prompt_events from anon, authenticated;
grant select on table public.prompt_events to authenticated;
grant all on table public.prompt_events to service_role;

create policy "Approved users can read their prompt events"
on public.prompt_events
for select
to authenticated
using (
  exists (
    select 1
    from public.provider_connections as connection
    where connection.id = prompt_events.connection_id
      and connection.owner_id = (select auth.uid())
  )
  and (select public.is_approved_user())
);

-- Every write below is an addition, so a redelivered batch would inflate the
-- totals rather than land on the same answer twice. OTLP exporters retry on any
-- failed or unacknowledged export, which makes redelivery routine rather than
-- exceptional, so each request is claimed here once by its Anthropic request id.
create table public.claude_request_ids (
  connection_id uuid not null references public.provider_connections (id) on delete cascade,
  request_id text not null,
  observed_at timestamptz not null default now(),
  primary key (connection_id, request_id)
);

-- Only ever read through the primary key on write; the index exists so old
-- claims can be pruned by age once the table is worth pruning.
create index claude_request_ids_observed_idx
on public.claude_request_ids (observed_at);

alter table public.claude_request_ids enable row level security;
revoke all on table public.claude_request_ids from anon, authenticated;
grant all on table public.claude_request_ids to service_role;

-- Adds one request's usage to its hourly bucket, its per-model cost line, and
-- the connection's lifetime total. Lifetime is maintained here so the dashboard
-- can add a Claude account total to a Codex one: Codex reports lifetime tokens
-- and a Claude total assembled from a 35-day bucket window would silently be a
-- smaller quantity wearing the same label.
create or replace function public.record_claude_usage(
  p_connection_id uuid,
  p_period_start timestamptz,
  p_model text,
  p_input_tokens bigint,
  p_output_tokens bigint,
  p_cached_input_tokens bigint,
  p_request_count bigint,
  p_cost_micros bigint
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if (select auth.role()) <> 'service_role' then
    raise exception 'service role required';
  end if;

  insert into public.usage_buckets as bucket (
    connection_id,
    period_start,
    period_end,
    model,
    input_tokens,
    output_tokens,
    cached_input_tokens,
    request_count,
    source_key
  )
  values (
    p_connection_id,
    p_period_start,
    p_period_start + interval '1 hour',
    p_model,
    p_input_tokens,
    p_output_tokens,
    p_cached_input_tokens,
    p_request_count,
    'otel'
  )
  on conflict (connection_id, period_start, period_end, model, source_key)
  do update set
    input_tokens = bucket.input_tokens + excluded.input_tokens,
    output_tokens = bucket.output_tokens + excluded.output_tokens,
    cached_input_tokens = bucket.cached_input_tokens + excluded.cached_input_tokens,
    request_count = bucket.request_count + excluded.request_count,
    observed_at = now();

  -- Cost rides on line_item rather than a column, which is what makes a
  -- per-model cost readable without another table.
  if p_cost_micros > 0 then
    insert into public.cost_buckets as cost (
      connection_id,
      period_start,
      period_end,
      amount,
      currency,
      cost_type,
      line_item,
      source_key
    )
    values (
      p_connection_id,
      p_period_start,
      p_period_start + interval '1 hour',
      p_cost_micros::numeric / 1000000,
      'USD',
      'estimated',
      p_model,
      'otel'
    )
    on conflict (connection_id, period_start, period_end, line_item, source_key)
    do update set
      amount = cost.amount + excluded.amount,
      observed_at = now();
  end if;

  insert into public.provider_usage_summaries as summary (
    connection_id,
    lifetime_tokens,
    observed_at
  )
  values (
    p_connection_id,
    p_input_tokens + p_output_tokens,
    now()
  )
  on conflict (connection_id)
  do update set
    lifetime_tokens =
      coalesce(summary.lifetime_tokens, 0) + excluded.lifetime_tokens,
    observed_at = now();
end;
$$;

-- Records the prompt itself. Deliberately leaves model and model_tokens alone:
-- the user_prompt event carries no model, and it often arrives after the
-- api_request events that already attributed one.
create or replace function public.record_claude_prompt(
  p_connection_id uuid,
  p_prompt_id text,
  p_session_id text,
  p_occurred_at timestamptz,
  p_excerpt text,
  p_prompt_length integer,
  p_command_name text,
  p_command_source text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if (select auth.role()) <> 'service_role' then
    raise exception 'service role required';
  end if;

  insert into public.prompt_events as event (
    connection_id,
    prompt_id,
    session_id,
    occurred_at,
    excerpt,
    prompt_length,
    command_name,
    command_source
  )
  values (
    p_connection_id,
    p_prompt_id,
    p_session_id,
    p_occurred_at,
    p_excerpt,
    coalesce(p_prompt_length, 0),
    p_command_name,
    p_command_source
  )
  on conflict (connection_id, prompt_id)
  do update set
    session_id = coalesce(excluded.session_id, event.session_id),
    occurred_at = least(event.occurred_at, excluded.occurred_at),
    excerpt = coalesce(excluded.excerpt, event.excerpt),
    prompt_length = greatest(event.prompt_length, excluded.prompt_length),
    command_name = coalesce(excluded.command_name, event.command_name),
    command_source = coalesce(excluded.command_source, event.command_source),
    observed_at = now();
end;
$$;

-- Adds one api_request's tokens to a prompt's per-model tally and re-picks the
-- dominant model. Creates the row when the api_request outruns its user_prompt.
create or replace function public.attribute_claude_prompt_model(
  p_connection_id uuid,
  p_prompt_id text,
  p_occurred_at timestamptz,
  p_model text,
  p_tokens bigint
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_tokens jsonb;
  v_model text;
begin
  if (select auth.role()) <> 'service_role' then
    raise exception 'service role required';
  end if;

  insert into public.prompt_events as event (
    connection_id,
    prompt_id,
    occurred_at,
    model,
    model_tokens
  )
  values (
    p_connection_id,
    p_prompt_id,
    p_occurred_at,
    p_model,
    jsonb_build_object(p_model, p_tokens)
  )
  on conflict (connection_id, prompt_id)
  do update set
    model_tokens = jsonb_set(
      event.model_tokens,
      array[p_model],
      to_jsonb(
        coalesce((event.model_tokens ->> p_model)::bigint, 0) + p_tokens
      )
    ),
    occurred_at = least(event.occurred_at, excluded.occurred_at),
    observed_at = now()
  returning event.model_tokens into v_tokens;

  select entry.key into v_model
  from jsonb_each_text(v_tokens) as entry(key, value)
  order by entry.value::bigint desc, entry.key
  limit 1;

  update public.prompt_events
  set model = coalesce(v_model, p_model)
  where connection_id = p_connection_id
    and prompt_id = p_prompt_id;
end;
$$;

revoke all on function public.record_claude_usage(uuid, timestamptz, text, bigint, bigint, bigint, bigint, bigint) from public, anon, authenticated;
revoke all on function public.record_claude_prompt(uuid, text, text, timestamptz, text, integer, text, text) from public, anon, authenticated;
revoke all on function public.attribute_claude_prompt_model(uuid, text, timestamptz, text, bigint) from public, anon, authenticated;

grant execute on function public.record_claude_usage(uuid, timestamptz, text, bigint, bigint, bigint, bigint, bigint) to service_role;
grant execute on function public.record_claude_prompt(uuid, text, text, timestamptz, text, integer, text, text) to service_role;
grant execute on function public.attribute_claude_prompt_model(uuid, text, timestamptz, text, bigint) to service_role;

comment on table public.prompt_events is
  'One row per Claude Code user prompt. Excerpt is null unless the project opted into OTEL_LOG_USER_PROMPTS.';
comment on column public.prompt_events.model is
  'The model that consumed the most tokens for this prompt, so per-model prompt counts partition the total.';
