-- Keywords, and the articles behind them.
--
-- The feed shows one card per article today, and at 1,261 articles that reads
-- as noise: seven `ggml-org/llama.cpp b106xx` rows, eight TanStack/query
-- releases, six SEC 8-K filings. Release bots crowd out the stories a person
-- opened the page for. A keyword is the thing worth scrolling; the articles are
-- what sits behind it.

-- Where a keyword's number comes from, and therefore what it means. This is the
-- one distinction the UI must never blur: Google reports people who searched,
-- while a derived keyword reports articles that mentioned it. A card showing
-- "20,000" beside a card showing "7" without saying which is which would be a
-- dashboard that lies.
create type public.news_trend_origin as enum ('search', 'coverage');

create table public.news_trends (
  id uuid primary key default gen_random_uuid(),
  term text not null,
  -- The comparable form: lowercased, punctuation folded, Unicode dashes mapped
  -- onto the ASCII one. Without that last part OpenAI's own "GPT‑5.6" and
  -- Hacker News's "GPT-5.6" are two keywords that never merge.
  term_key text not null,
  category public.news_category not null,
  origin public.news_trend_origin not null,
  -- Set for search trends, which are per-region. Null for derived keywords,
  -- which are not about anywhere.
  geo text,
  -- Only ever set for origin = 'search'. A floor, not a count: Google publishes
  -- "200+", so the UI says "200+" rather than inventing precision.
  search_volume integer check (search_volume is null or search_volume >= 0),
  article_count integer not null default 0 check (article_count >= 0),
  source_count integer not null default 0 check (source_count >= 0),
  picture_url text,
  -- Time-independent, as news_items.hotness is, and for the same reason: a
  -- score with now() baked in is stale the moment it is written.
  hotness numeric not null default 0,
  half_life_hours numeric not null default 12 check (half_life_hours > 0),
  effective_at timestamptz not null,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  summary_md text check (summary_md is null or length(summary_md) <= 20000),
  summary_model text,
  summary_prompt_version text,
  summary_status public.news_summary_status not null default 'pending',
  summary_error text,
  summarized_at timestamptz,
  parser_version text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  -- A term means something different per category and per region: "nghệ an"
  -- trending in Vietnam is not the same row as anywhere else.
  unique (term_key, category, geo),
  -- Enforced rather than trusted, because the whole honesty of the feature
  -- rests on it.
  constraint news_trends_volume_only_for_search
    check (origin = 'search' or search_volume is null)
);

create index news_trends_feed_idx
on public.news_trends (category, hotness desc, effective_at desc);

create index news_trends_term_idx on public.news_trends (term_key);

-- The articles behind a keyword. Two kinds arrive here: rows Google names in
-- its <ht:news_item> children, which we have never fetched and so have no item
-- of our own for, and our own collected items for derived keywords. item_id is
-- null for the first kind rather than forcing a fake item row.
create table public.news_trend_coverage (
  id bigint generated by default as identity primary key,
  trend_id uuid not null references public.news_trends (id) on delete cascade,
  item_id uuid references public.news_items (id) on delete set null,
  title text not null,
  url text not null,
  canonical_url text not null,
  source_name text not null default 'Unknown',
  published_at timestamptz,
  position integer not null default 0,
  created_at timestamptz not null default now(),
  unique (trend_id, canonical_url)
);

create index news_trend_coverage_trend_idx
on public.news_trend_coverage (trend_id, position);

-- One point per keyword per day, the shape news_watch_metrics already uses, so
-- "is it climbing" is answerable without a second table design.
create table public.news_trend_metrics (
  id bigint generated by default as identity primary key,
  trend_id uuid not null references public.news_trends (id) on delete cascade,
  captured_on date not null,
  search_volume integer check (search_volume is null or search_volume >= 0),
  article_count integer check (article_count is null or article_count >= 0),
  unique (trend_id, captured_on)
);

create index news_trend_metrics_series_idx
on public.news_trend_metrics (trend_id, captured_on desc);

-- Terms co-occurring across a keyword's coverage.
--
-- Deliberately not called "related searches". Google's related-queries endpoint
-- needs a signed widget token and answers 400 without one, and that flow would
-- likely be blocked from this datacenter the way Reddit already is. These are
-- terms in the coverage, and the UI says exactly that.
create table public.news_trend_terms (
  id bigint generated by default as identity primary key,
  trend_id uuid not null references public.news_trends (id) on delete cascade,
  term text not null,
  weight integer not null default 0 check (weight >= 0),
  article_count integer not null default 0 check (article_count >= 0),
  unique (trend_id, term)
);

create index news_trend_terms_trend_idx
on public.news_trend_terms (trend_id, weight desc);

alter table public.news_trends enable row level security;
alter table public.news_trend_coverage enable row level security;
alter table public.news_trend_metrics enable row level security;
alter table public.news_trend_terms enable row level security;

revoke all on table public.news_trends from anon, authenticated;
revoke all on table public.news_trend_coverage from anon, authenticated;
revoke all on table public.news_trend_metrics from anon, authenticated;
revoke all on table public.news_trend_terms from anon, authenticated;

grant select on table public.news_trends to authenticated;
grant select on table public.news_trend_coverage to authenticated;
grant select on table public.news_trend_metrics to authenticated;
grant select on table public.news_trend_terms to authenticated;

grant all on table public.news_trends to service_role;
grant all on table public.news_trend_coverage to service_role;
grant all on table public.news_trend_metrics to service_role;
grant all on table public.news_trend_terms to service_role;
grant usage, select on all sequences in schema public to service_role;

create policy "Approved users can read news trends"
on public.news_trends for select to authenticated
using ((select public.is_approved_user()));

create policy "Approved users can read news trend coverage"
on public.news_trend_coverage for select to authenticated
using ((select public.is_approved_user()));

create policy "Approved users can read news trend metrics"
on public.news_trend_metrics for select to authenticated
using ((select public.is_approved_user()));

create policy "Approved users can read news trend terms"
on public.news_trend_terms for select to authenticated
using ((select public.is_approved_user()));

-- The keyword equivalent of set_news_summary, and admin-only for the same
-- reason: the route decides what to draw, this decides what is allowed.
create or replace function public.set_news_trend_summary(
  p_trend_id uuid,
  p_summary_md text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not (select public.is_approved_admin()) then
    raise exception 'an approved admin is required';
  end if;

  if p_summary_md is not null and length(p_summary_md) > 20000 then
    raise exception 'summary exceeds the stored length';
  end if;

  update public.news_trends
  set summary_md = p_summary_md,
      summary_status = case
        when p_summary_md is null then 'pending'::public.news_summary_status
        else 'summarized'::public.news_summary_status
      end,
      summary_model = case when p_summary_md is null then null else 'manual' end,
      summary_prompt_version = null,
      summary_error = null,
      summarized_at = case when p_summary_md is null then null else now() end,
      updated_at = now()
  where id = p_trend_id;

  if not found then
    raise exception 'news trend was not found';
  end if;
end;
$$;

revoke all on function public.set_news_trend_summary(uuid, text) from public, anon;
grant execute on function public.set_news_trend_summary(uuid, text) to authenticated;

comment on table public.news_trends is
  'One keyword per row. origin says what its number means: search volume from Google, or article count derived from what we collected. The two are never formatted the same way.';

comment on table public.news_trend_terms is
  'Terms co-occurring in a keyword''s coverage. Not search data — Google does not expose related queries to us — and the UI must not describe them as such.';
