-- The news feed: public sources collected server-side, ranked, and summarized.
--
-- Shaped after the job market deliberately. Both are "fetch public feeds, keep
-- the raw payload private, expose a normalized row under RLS, audit every run
-- per source", and the second one should not invent a second vocabulary for it.

create type public.news_category as enum ('ai', 'stack', 'genz');

create type public.news_summary_status as enum (
  'pending',
  'extracted',
  'summarized',
  'failed',
  'skipped'
);

create type public.news_sync_status as enum (
  'running',
  'succeeded',
  'partial',
  'failed'
);

create table public.news_sources (
  id text primary key,
  name text not null,
  source_type text not null,
  source_url text not null,
  -- A prior, not a verdict. Hacker News carries all three categories, so it
  -- stores null and every item is routed on its own merits. A single-topic
  -- source stores its category and sets category_exclusive so the router stops
  -- there rather than second-guessing it from a title.
  category public.news_category,
  category_exclusive boolean not null default false,
  -- Multiplies the blended score, so a low-signal firehose cannot outrank a
  -- curated feed by volume alone.
  weight numeric(3, 2) not null default 1.00
    check (weight > 0 and weight <= 2),
  enabled boolean not null default true,
  requires_secret boolean not null default false,
  last_synced_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (not category_exclusive or category is not null)
);

create table public.news_sync_runs (
  id uuid primary key default gen_random_uuid(),
  requested_by uuid not null references public.profiles (id) on delete restrict,
  status public.news_sync_status not null default 'running',
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  sources_attempted integer not null default 0 check (sources_attempted >= 0),
  sources_succeeded integer not null default 0 check (sources_succeeded >= 0),
  items_fetched integer not null default 0 check (items_fetched >= 0),
  items_created integer not null default 0 check (items_created >= 0),
  items_updated integer not null default 0 check (items_updated >= 0),
  error text
);

-- One collection at a time. A second run would double-count the attention
-- snapshots that velocity is derived from.
create unique index news_sync_runs_one_running_unique
on public.news_sync_runs ((true))
where status = 'running';

create table public.news_sync_source_runs (
  id bigint generated by default as identity primary key,
  run_id uuid not null references public.news_sync_runs (id) on delete cascade,
  source_id text not null references public.news_sources (id) on delete cascade,
  status text not null check (status in ('succeeded', 'skipped', 'failed')),
  items_fetched integer not null default 0 check (items_fetched >= 0),
  items_kept integer not null default 0 check (items_kept >= 0),
  duplicate_items integer not null default 0 check (duplicate_items >= 0),
  stop_reason text,
  error text,
  completed_at timestamptz not null default now(),
  unique (run_id, source_id)
);

create table public.news_items (
  id uuid primary key default gen_random_uuid(),
  source_id text not null references public.news_sources (id) on delete restrict,
  external_id text not null,
  url text not null,
  -- Tracking parameters stripped, host lowercased, entity families collapsed —
  -- arxiv:2608.20169 rather than four spellings of the same paper.
  canonical_url text not null,
  url_key text not null,
  title text not null,
  -- The headline reduced to comparable words. Two feeds rarely word a headline
  -- identically, so URL matching alone leaves the same story in the feed four
  -- times.
  title_key text not null default '',
  author text,
  excerpt text not null default '',
  category public.news_category not null,
  category_reason text not null default 'lexicon',
  -- The first item of a cluster owns the id every later duplicate adopts.
  cluster_id uuid not null,
  points integer check (points is null or points >= 0),
  comments integer check (comments is null or comments >= 0),
  attention numeric,
  velocity numeric,
  -- Time-independent. Decay is applied at query time, because a stored value
  -- that embeds now() is stale the moment it is written.
  hotness numeric not null default 0,
  half_life_hours numeric not null default 8 check (half_life_hours > 0),
  published_at timestamptz,
  -- published_at, clamped to first_seen_at and to at most 48h before it. A feed
  -- that backfills its archive must not repopulate the front page.
  effective_at timestamptz not null,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  summary_md text check (summary_md is null or length(summary_md) <= 20000),
  summary_model text,
  summary_prompt_version text,
  summary_status public.news_summary_status not null default 'pending',
  summary_error text,
  summarized_at timestamptz,
  content_hash text not null,
  parser_version text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (source_id, external_id)
);

create index news_items_feed_idx
on public.news_items (category, hotness desc, effective_at desc);

create index news_items_url_key_idx on public.news_items (url_key);

create index news_items_cluster_idx
on public.news_items (cluster_id, hotness desc);

create index news_items_summary_queue_idx
on public.news_items (summary_status, hotness desc)
where summary_status in ('pending', 'extracted');

-- One row per item per collection. Velocity is the change between the last two,
-- which is the difference between "this is big" and "this is happening now".
create table public.news_item_metrics (
  id bigint generated by default as identity primary key,
  item_id uuid not null references public.news_items (id) on delete cascade,
  captured_at timestamptz not null default now(),
  attention numeric not null,
  unique (item_id, captured_at)
);

create index news_item_metrics_recent_idx
on public.news_item_metrics (item_id, captured_at desc);

-- Gen Z slang has no feed. The tracked half is a watchlist somebody curates,
-- and the numbers underneath it come from sources that do answer a machine.
create table public.news_watch_terms (
  id uuid primary key default gen_random_uuid(),
  term text not null,
  locale text not null default 'en' check (locale in ('en', 'vi')),
  wiki_article text,
  added_by uuid not null references public.profiles (id) on delete restrict,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (term, locale)
);

create table public.news_watch_metrics (
  id bigint generated by default as identity primary key,
  term_id uuid not null references public.news_watch_terms (id) on delete cascade,
  captured_on date not null,
  wiki_views integer check (wiki_views is null or wiki_views >= 0),
  definitions integer check (definitions is null or definitions >= 0),
  thumbs_up integer check (thumbs_up is null or thumbs_up >= 0),
  unique (term_id, captured_on)
);

create index news_watch_metrics_series_idx
on public.news_watch_metrics (term_id, captured_on desc);

create table private.news_item_payloads (
  item_id uuid primary key references public.news_items (id) on delete cascade,
  raw_payload jsonb not null,
  updated_at timestamptz not null default now(),
  check (jsonb_typeof(raw_payload) = 'object')
);

-- Article bodies are fetched from the open web and are the input a summarizing
-- model reads, which makes them prompt-injection carriers. They stay in the
-- schema the browser has no grants on, and only the extract the model needs is
-- kept.
create table private.news_article_text (
  item_id uuid primary key references public.news_items (id) on delete cascade,
  extracted_text text not null,
  extracted_at timestamptz not null default now()
);

alter table public.news_sources enable row level security;
alter table public.news_sync_runs enable row level security;
alter table public.news_sync_source_runs enable row level security;
alter table public.news_items enable row level security;
alter table public.news_item_metrics enable row level security;
alter table public.news_watch_terms enable row level security;
alter table public.news_watch_metrics enable row level security;
alter table private.news_item_payloads enable row level security;
alter table private.news_article_text enable row level security;

revoke all on table public.news_sources from anon, authenticated;
revoke all on table public.news_sync_runs from anon, authenticated;
revoke all on table public.news_sync_source_runs from anon, authenticated;
revoke all on table public.news_items from anon, authenticated;
revoke all on table public.news_item_metrics from anon, authenticated;
revoke all on table public.news_watch_terms from anon, authenticated;
revoke all on table public.news_watch_metrics from anon, authenticated;

grant select on table public.news_sources to authenticated;
grant select on table public.news_sync_runs to authenticated;
grant select on table public.news_sync_source_runs to authenticated;
grant select on table public.news_items to authenticated;
grant select on table public.news_item_metrics to authenticated;
grant select on table public.news_watch_terms to authenticated;
grant select on table public.news_watch_metrics to authenticated;

grant all on table public.news_sources to service_role;
grant all on table public.news_sync_runs to service_role;
grant all on table public.news_sync_source_runs to service_role;
grant all on table public.news_items to service_role;
grant all on table public.news_item_metrics to service_role;
grant all on table public.news_watch_terms to service_role;
grant all on table public.news_watch_metrics to service_role;
grant all on table private.news_item_payloads to service_role;
grant all on table private.news_article_text to service_role;
grant usage, select on all sequences in schema public to service_role;

create policy "Approved users can read news sources"
on public.news_sources for select to authenticated
using ((select public.is_approved_user()));

create policy "Approved users can read news sync runs"
on public.news_sync_runs for select to authenticated
using ((select public.is_approved_user()));

create policy "Approved users can read news source sync runs"
on public.news_sync_source_runs for select to authenticated
using ((select public.is_approved_user()));

create policy "Approved users can read news items"
on public.news_items for select to authenticated
using ((select public.is_approved_user()));

create policy "Approved users can read news item metrics"
on public.news_item_metrics for select to authenticated
using ((select public.is_approved_user()));

-- The same pair of questions is_approved_user answers, plus the one the watch
-- list needs: approval opens the workspace, the role decides who may change
-- what everyone else sees.
create or replace function public.is_approved_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles
    where id = (select auth.uid())
      and status = 'approved'
      and role = 'admin'
  );
$$;

revoke all on function public.is_approved_admin() from public;
grant execute on function public.is_approved_admin() to authenticated;

create policy "Approved users can read news watch terms"
on public.news_watch_terms for select to authenticated
using ((select public.is_approved_user()));

-- The watch list is the one collector input a person curates, so it is the one
-- table the browser writes to. added_by is pinned to the caller rather than
-- accepted from them, so the row cannot be attributed to somebody else.
grant insert, delete on table public.news_watch_terms to authenticated;

create policy "Approved admins can add news watch terms"
on public.news_watch_terms for insert to authenticated
with check (
  (select public.is_approved_admin()) and added_by = (select auth.uid())
);

create policy "Approved admins can remove news watch terms"
on public.news_watch_terms for delete to authenticated
using ((select public.is_approved_admin()));

create policy "Approved users can read news watch metrics"
on public.news_watch_metrics for select to authenticated
using ((select public.is_approved_user()));

-- A summary is the one field a human is expected to correct, so the browser
-- writes it directly rather than through a function. Everything else about an
-- item is derived by the collector and stays read-only.
--
-- Admin-only, and asserted here rather than trusted from the caller: the route
-- decides what to draw, this decides what is allowed.
create or replace function public.set_news_summary(
  p_item_id uuid,
  p_summary_md text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not (select public.is_approved_admin()) then
    raise exception 'an approved admin is required';
  end if;

  if p_summary_md is not null and length(p_summary_md) > 20000 then
    raise exception 'summary exceeds the stored length';
  end if;

  update public.news_items
  set summary_md = p_summary_md,
      summary_status = case
        when p_summary_md is null then 'extracted'::public.news_summary_status
        else 'summarized'::public.news_summary_status
      end,
      summary_model = case when p_summary_md is null then null else 'manual' end,
      summary_prompt_version = null,
      summary_error = null,
      summarized_at = case when p_summary_md is null then null else now() end,
      updated_at = now()
  where id = p_item_id;

  if not found then
    raise exception 'news item was not found';
  end if;
end;
$$;

revoke all on function public.set_news_summary(uuid, text) from public, anon;
grant execute on function public.set_news_summary(uuid, text) to authenticated;

-- private is unreachable from PostgREST, so the collector reaches it through a
-- definer function that asserts the service role, matching store_job_payloads.
create or replace function public.store_news_payloads(p_payloads jsonb)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if (select auth.role()) <> 'service_role' then
    raise exception 'service role required';
  end if;

  if jsonb_typeof(p_payloads) <> 'array' then
    raise exception 'news payloads must be an array';
  end if;

  insert into private.news_item_payloads as stored (
    item_id,
    raw_payload,
    updated_at
  )
  select
    (payload ->> 'item_id')::uuid,
    payload -> 'raw_payload',
    now()
  from jsonb_array_elements(p_payloads) as payload
  on conflict (item_id) do update
  set raw_payload = excluded.raw_payload,
      updated_at = excluded.updated_at;
end;
$$;

revoke all on function public.store_news_payloads(jsonb) from public, anon, authenticated;
grant execute on function public.store_news_payloads(jsonb) to service_role;

create or replace function public.store_news_article_text(
  p_item_id uuid,
  p_extracted_text text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if (select auth.role()) <> 'service_role' then
    raise exception 'service role required';
  end if;

  insert into private.news_article_text as stored (
    item_id,
    extracted_text,
    extracted_at
  )
  values (p_item_id, p_extracted_text, now())
  on conflict (item_id) do update
  set extracted_text = excluded.extracted_text,
      extracted_at = excluded.extracted_at;
end;
$$;

revoke all on function public.store_news_article_text(uuid, text)
  from public, anon, authenticated;
grant execute on function public.store_news_article_text(uuid, text) to service_role;

create or replace function public.read_news_article_text(p_item_id uuid)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_text text;
begin
  if (select auth.role()) <> 'service_role' then
    raise exception 'service role required';
  end if;

  select stored.extracted_text into v_text
  from private.news_article_text as stored
  where stored.item_id = p_item_id;

  return v_text;
end;
$$;

revoke all on function public.read_news_article_text(uuid)
  from public, anon, authenticated;
grant execute on function public.read_news_article_text(uuid) to service_role;

insert into public.news_sources (
  id, name, source_type, source_url, category, category_exclusive, weight
)
values
  -- AI
  ('hn-frontpage', 'Hacker News front page', 'hn-algolia-front', 'https://news.ycombinator.com', null, false, 1.00),
  ('hn-ai-watch', 'Hacker News AI watch', 'hn-algolia-query', 'https://hn.algolia.com', 'ai', false, 0.80),
  ('lobsters-ai', 'Lobsters AI', 'lobsters-tag', 'https://lobste.rs/t/ai', 'ai', true, 0.90),
  ('hf-models', 'Hugging Face trending models', 'hf-models', 'https://huggingface.co/models', 'ai', true, 1.00),
  ('hf-papers', 'Hugging Face daily papers', 'hf-papers', 'https://huggingface.co/papers', 'ai', true, 1.00),
  ('openai-news', 'OpenAI news', 'rss', 'https://openai.com/news/rss.xml', 'ai', true, 1.00),
  ('deepmind-blog', 'Google DeepMind blog', 'rss', 'https://deepmind.google/blog/rss.xml', 'ai', true, 0.90),
  ('mistral-news', 'Mistral AI news', 'rss', 'https://mistral.ai/news/rss', 'ai', true, 0.80),
  ('anthropic-news', 'Anthropic news (community mirror)', 'rss', 'https://raw.githubusercontent.com/taobojlen/anthropic-rss-feed/main/anthropic_news_rss.xml', 'ai', true, 0.80),
  ('openai-status', 'OpenAI status', 'statuspage-incidents', 'https://status.openai.com', 'ai', true, 1.00),
  ('claude-status', 'Claude status', 'statuspage-summary', 'https://status.claude.com', 'ai', true, 1.00),
  ('arxiv-ai', 'arXiv cs.AI and cs.CL', 'arxiv', 'https://export.arxiv.org', 'ai', true, 0.50),
  ('github-trending-ai', 'GitHub trending (AI)', 'github-trending', 'https://github.com/trending', 'ai', false, 0.80),

  -- Stack
  ('hn-stack', 'Hacker News 100+ points', 'hnrss', 'https://hnrss.org/frontpage', null, false, 1.00),
  ('lobsters-hot', 'Lobsters hottest', 'lobsters-hot', 'https://lobste.rs/hottest', null, false, 0.90),
  ('devto-top', 'dev.to top of the week', 'devto', 'https://dev.to', 'stack', false, 0.60),
  ('github-releases', 'GitHub releases', 'github-releases', 'https://github.com', null, false, 1.00),
  ('supabase-blog', 'Supabase blog', 'rss', 'https://supabase.com/rss.xml', 'stack', true, 0.80),
  ('vercel-changelog', 'Vercel changelog', 'rss', 'https://vercel.com/atom', 'stack', true, 0.70),
  ('techcrunch-layoffs', 'TechCrunch layoffs', 'rss', 'https://techcrunch.com/tag/layoffs/feed/', 'stack', true, 1.00),
  ('techcrunch-hiring', 'TechCrunch hiring', 'rss', 'https://techcrunch.com/tag/hiring/feed/', 'stack', true, 0.90),
  ('verge-tech', 'The Verge tech', 'rss', 'https://www.theverge.com/tech/rss/index.xml', 'stack', true, 0.80),
  ('sec-restructuring', 'SEC 8-K restructuring filings', 'sec-edgar', 'https://efts.sec.gov', 'stack', true, 1.00),

  -- GenZ
  ('trends-vn', 'Google Trends Vietnam', 'google-trends', 'https://trends.google.com/trending/rss?geo=VN', 'genz', true, 1.00),
  ('trends-us', 'Google Trends United States', 'google-trends', 'https://trends.google.com/trending/rss?geo=US', 'genz', true, 0.80),
  ('kenh14-hoc-duong', 'Kênh14 học đường', 'rss', 'https://kenh14.vn/hoc-duong.rss', 'genz', true, 1.00),
  ('kenh14-doi-song', 'Kênh14 đời sống', 'rss', 'https://kenh14.vn/doi-song.rss', 'genz', true, 0.90),
  ('tuoitre-nhip-song-tre', 'Tuổi Trẻ nhịp sống trẻ', 'rss', 'https://tuoitre.vn/rss/nhip-song-tre.rss', 'genz', true, 1.00),
  ('thanhnien-gioi-tre', 'Thanh Niên giới trẻ', 'rss', 'https://thanhnien.vn/rss/gioi-tre.rss', 'genz', true, 0.90),
  ('vnexpress-doi-song', 'VnExpress đời sống', 'rss', 'https://vnexpress.net/rss/doi-song.rss', 'genz', true, 0.80),
  ('merriam-wotd', 'Merriam-Webster word of the day', 'rss', 'https://www.merriam-webster.com/wotd/feed/rss2', 'genz', true, 0.50),
  ('reddit-genz', 'Reddit Gen Z rotation', 'reddit-atom', 'https://www.reddit.com', 'genz', true, 0.70);

comment on table public.news_items is
  'Normalized public-feed items shared by approved Hub William users. Raw upstream payloads and extracted article bodies stay in the private schema.';

comment on column public.news_items.hotness is
  'Time-independent blended score. Decay is applied at query time so the ranking cannot go stale between collections.';

comment on column public.news_sources.category is
  'A routing prior. Null means the source is mixed and every item is classified on its own merits.';

comment on function public.set_news_summary(uuid, text) is
  'Lets an approved admin write or clear an item summary. The only browser-writable field on a news item.';
