create type public.ai_provider as enum ('openai', 'anthropic', 'google');
create type public.provider_connection_method as enum ('admin_key', 'oauth', 'collector');
create type public.provider_connection_status as enum (
  'verifying',
  'connected',
  'needs_attention',
  'disconnected'
);
create type public.usage_cost_type as enum ('reported', 'estimated');

create table public.provider_connections (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles (id) on delete cascade,
  provider public.ai_provider not null,
  connection_method public.provider_connection_method not null,
  status public.provider_connection_status not null default 'verifying',
  display_name text not null,
  external_account_id text,
  email text,
  workspace_name text,
  history_starts_at timestamptz not null,
  capabilities jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  last_synced_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (jsonb_typeof(capabilities) = 'object'),
  check (jsonb_typeof(metadata) = 'object')
);

create table public.usage_buckets (
  id bigint generated by default as identity primary key,
  connection_id uuid not null references public.provider_connections (id) on delete cascade,
  period_start timestamptz not null,
  period_end timestamptz not null,
  model text not null default 'unknown',
  input_tokens bigint not null default 0 check (input_tokens >= 0),
  output_tokens bigint not null default 0 check (output_tokens >= 0),
  cached_input_tokens bigint not null default 0 check (cached_input_tokens >= 0),
  request_count bigint not null default 0 check (request_count >= 0),
  source_key text not null,
  observed_at timestamptz not null default now(),
  check (period_end > period_start)
);

create unique index usage_buckets_source_unique
on public.usage_buckets (connection_id, period_start, period_end, model, source_key);

create index usage_buckets_connection_period_idx
on public.usage_buckets (connection_id, period_start desc);

create table public.cost_buckets (
  id bigint generated by default as identity primary key,
  connection_id uuid not null references public.provider_connections (id) on delete cascade,
  period_start timestamptz not null,
  period_end timestamptz not null,
  amount numeric(20, 8) not null check (amount >= 0),
  currency text not null default 'USD',
  cost_type public.usage_cost_type not null,
  line_item text not null default 'total',
  source_key text not null,
  observed_at timestamptz not null default now(),
  check (period_end > period_start),
  check (char_length(currency) = 3)
);

create unique index cost_buckets_source_unique
on public.cost_buckets (connection_id, period_start, period_end, line_item, source_key);

create index cost_buckets_connection_period_idx
on public.cost_buckets (connection_id, period_start desc);

create table public.usage_limits (
  id bigint generated by default as identity primary key,
  connection_id uuid not null references public.provider_connections (id) on delete cascade,
  metric_key text not null,
  label text not null,
  kind text not null,
  unit text not null,
  scope text not null,
  model text not null default 'all',
  window_name text,
  used numeric,
  limit_value numeric,
  remaining numeric,
  resets_at timestamptz,
  observed_at timestamptz not null default now(),
  check (used is null or used >= 0),
  check (limit_value is null or limit_value >= 0),
  check (remaining is null or remaining >= 0)
);

create unique index usage_limits_metric_unique
on public.usage_limits (connection_id, metric_key, model);

create table public.provider_sync_runs (
  id uuid primary key default gen_random_uuid(),
  connection_id uuid not null references public.provider_connections (id) on delete cascade,
  status text not null check (status in ('running', 'succeeded', 'failed')),
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  error text
);

create index provider_sync_runs_connection_started_idx
on public.provider_sync_runs (connection_id, started_at desc);

create unique index provider_sync_runs_one_running_unique
on public.provider_sync_runs (connection_id)
where status = 'running';

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table private.provider_credentials (
  connection_id uuid primary key references public.provider_connections (id) on delete cascade,
  credential_kind text not null,
  ciphertext text not null,
  initialization_vector text not null,
  expires_at timestamptz,
  updated_at timestamptz not null default now()
);

create table private.provider_oauth_states (
  state_hash text primary key,
  owner_id uuid not null references public.profiles (id) on delete cascade,
  provider public.ai_provider not null,
  project_id text not null,
  redirect_to text not null,
  code_verifier text not null,
  history_starts_at timestamptz not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

alter table public.provider_connections enable row level security;
alter table public.usage_buckets enable row level security;
alter table public.cost_buckets enable row level security;
alter table public.usage_limits enable row level security;
alter table public.provider_sync_runs enable row level security;
alter table private.provider_credentials enable row level security;
alter table private.provider_oauth_states enable row level security;

revoke all on table public.provider_connections from anon, authenticated;
revoke all on table public.usage_buckets from anon, authenticated;
revoke all on table public.cost_buckets from anon, authenticated;
revoke all on table public.usage_limits from anon, authenticated;
revoke all on table public.provider_sync_runs from anon, authenticated;

grant select on table public.provider_connections to authenticated;
grant select on table public.usage_buckets to authenticated;
grant select on table public.cost_buckets to authenticated;
grant select on table public.usage_limits to authenticated;
grant select on table public.provider_sync_runs to authenticated;

grant all on table public.provider_connections to service_role;
grant all on table public.usage_buckets to service_role;
grant all on table public.cost_buckets to service_role;
grant all on table public.usage_limits to service_role;
grant all on table public.provider_sync_runs to service_role;
grant usage, select on all sequences in schema public to service_role;

create policy "Approved users can read their provider connections"
on public.provider_connections
for select
to authenticated
using (
  owner_id = (select auth.uid())
  and (select public.is_approved_user())
);

create policy "Approved users can read their usage buckets"
on public.usage_buckets
for select
to authenticated
using (
  exists (
    select 1
    from public.provider_connections as connection
    where connection.id = usage_buckets.connection_id
      and connection.owner_id = (select auth.uid())
  )
  and (select public.is_approved_user())
);

create policy "Approved users can read their cost buckets"
on public.cost_buckets
for select
to authenticated
using (
  exists (
    select 1
    from public.provider_connections as connection
    where connection.id = cost_buckets.connection_id
      and connection.owner_id = (select auth.uid())
  )
  and (select public.is_approved_user())
);

create policy "Approved users can read their usage limits"
on public.usage_limits
for select
to authenticated
using (
  exists (
    select 1
    from public.provider_connections as connection
    where connection.id = usage_limits.connection_id
      and connection.owner_id = (select auth.uid())
  )
  and (select public.is_approved_user())
);

create policy "Approved users can read their sync history"
on public.provider_sync_runs
for select
to authenticated
using (
  exists (
    select 1
    from public.provider_connections as connection
    where connection.id = provider_sync_runs.connection_id
      and connection.owner_id = (select auth.uid())
  )
  and (select public.is_approved_user())
);

create or replace function public.touch_provider_connection()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger before_provider_connection_update
before update on public.provider_connections
for each row execute procedure public.touch_provider_connection();

create or replace function public.store_provider_credential(
  p_connection_id uuid,
  p_credential_kind text,
  p_ciphertext text,
  p_initialization_vector text,
  p_expires_at timestamptz default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if (select auth.role()) <> 'service_role' then
    raise exception 'service role required';
  end if;

  insert into private.provider_credentials (
    connection_id,
    credential_kind,
    ciphertext,
    initialization_vector,
    expires_at
  )
  values (
    p_connection_id,
    p_credential_kind,
    p_ciphertext,
    p_initialization_vector,
    p_expires_at
  )
  on conflict (connection_id) do update
  set credential_kind = excluded.credential_kind,
      ciphertext = excluded.ciphertext,
      initialization_vector = excluded.initialization_vector,
      expires_at = excluded.expires_at,
      updated_at = now();
end;
$$;

create or replace function public.read_provider_credential(p_connection_id uuid)
returns table (
  credential_kind text,
  ciphertext text,
  initialization_vector text,
  expires_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  if (select auth.role()) <> 'service_role' then
    raise exception 'service role required';
  end if;

  return query
  select
    credential.credential_kind,
    credential.ciphertext,
    credential.initialization_vector,
    credential.expires_at
  from private.provider_credentials as credential
  where credential.connection_id = p_connection_id;
end;
$$;

create or replace function public.delete_provider_credential(p_connection_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if (select auth.role()) <> 'service_role' then
    raise exception 'service role required';
  end if;

  delete from private.provider_credentials
  where connection_id = p_connection_id;
end;
$$;

create or replace function public.store_provider_oauth_state(
  p_state_hash text,
  p_owner_id uuid,
  p_provider public.ai_provider,
  p_project_id text,
  p_redirect_to text,
  p_code_verifier text,
  p_history_starts_at timestamptz,
  p_expires_at timestamptz
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if (select auth.role()) <> 'service_role' then
    raise exception 'service role required';
  end if;

  delete from private.provider_oauth_states
  where expires_at <= now();

  insert into private.provider_oauth_states (
    state_hash,
    owner_id,
    provider,
    project_id,
    redirect_to,
    code_verifier,
    history_starts_at,
    expires_at
  )
  values (
    p_state_hash,
    p_owner_id,
    p_provider,
    p_project_id,
    p_redirect_to,
    p_code_verifier,
    p_history_starts_at,
    p_expires_at
  );
end;
$$;

create or replace function public.consume_provider_oauth_state(p_state_hash text)
returns table (
  owner_id uuid,
  provider public.ai_provider,
  project_id text,
  redirect_to text,
  code_verifier text,
  history_starts_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  if (select auth.role()) <> 'service_role' then
    raise exception 'service role required';
  end if;

  return query
  delete from private.provider_oauth_states as oauth_state
  where oauth_state.state_hash = p_state_hash
    and oauth_state.expires_at > now()
  returning
    oauth_state.owner_id,
    oauth_state.provider,
    oauth_state.project_id,
    oauth_state.redirect_to,
    oauth_state.code_verifier,
    oauth_state.history_starts_at;
end;
$$;

revoke all on function public.store_provider_credential(uuid, text, text, text, timestamptz) from public, anon, authenticated;
revoke all on function public.read_provider_credential(uuid) from public, anon, authenticated;
revoke all on function public.delete_provider_credential(uuid) from public, anon, authenticated;
revoke all on function public.store_provider_oauth_state(text, uuid, public.ai_provider, text, text, text, timestamptz, timestamptz) from public, anon, authenticated;
revoke all on function public.consume_provider_oauth_state(text) from public, anon, authenticated;

grant execute on function public.store_provider_credential(uuid, text, text, text, timestamptz) to service_role;
grant execute on function public.read_provider_credential(uuid) to service_role;
grant execute on function public.delete_provider_credential(uuid) to service_role;
grant execute on function public.store_provider_oauth_state(text, uuid, public.ai_provider, text, text, text, timestamptz, timestamptz) to service_role;
grant execute on function public.consume_provider_oauth_state(text) to service_role;

comment on table public.provider_connections is
  'Verified external usage sources owned by an approved Hub William user.';
comment on table public.usage_buckets is
  'Provider-reported token usage normalized into time and model buckets.';
comment on table public.usage_limits is
  'Optional provider-reported quota and rate-limit metrics; missing values are never inferred.';
comment on table private.provider_credentials is
  'AES-GCM encrypted provider credentials. Only service-role RPC functions can access this table.';
