create type public.job_sync_status as enum (
  'running',
  'succeeded',
  'partial',
  'failed'
);

create type public.job_requirement_kind as enum (
  'required',
  'preferred',
  'mentioned'
);

create table public.job_sources (
  id text primary key,
  name text not null,
  source_type text not null,
  source_url text not null,
  enabled boolean not null default true,
  requires_secret boolean not null default false,
  last_synced_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.job_sync_runs (
  id uuid primary key default gen_random_uuid(),
  requested_by uuid not null references public.profiles (id) on delete restrict,
  status public.job_sync_status not null default 'running',
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  sources_attempted integer not null default 0 check (sources_attempted >= 0),
  sources_succeeded integer not null default 0 check (sources_succeeded >= 0),
  jobs_fetched integer not null default 0 check (jobs_fetched >= 0),
  jobs_created integer not null default 0 check (jobs_created >= 0),
  jobs_updated integer not null default 0 check (jobs_updated >= 0),
  error text
);

create unique index job_sync_runs_one_running_unique
on public.job_sync_runs ((true))
where status = 'running';

create table public.job_sync_source_runs (
  id bigint generated by default as identity primary key,
  run_id uuid not null references public.job_sync_runs (id) on delete cascade,
  source_id text not null references public.job_sources (id) on delete cascade,
  status text not null check (status in ('succeeded', 'skipped', 'failed')),
  jobs_fetched integer not null default 0 check (jobs_fetched >= 0),
  error text,
  completed_at timestamptz not null default now(),
  unique (run_id, source_id)
);

create table public.job_postings (
  id uuid primary key default gen_random_uuid(),
  source_id text not null references public.job_sources (id) on delete restrict,
  external_id text not null,
  source_url text not null,
  title text not null,
  company_name text not null,
  company_logo_url text,
  description_text text not null,
  description_quality text not null default 'full'
    check (description_quality in ('full', 'snippet')),
  excerpt text not null default '',
  category text not null,
  location_city text not null,
  location_text text not null,
  remote boolean not null default false,
  employment_type text,
  seniority text not null default 'unknown',
  seniority_source text not null default 'unknown'
    check (seniority_source in ('explicit', 'inferred', 'unknown')),
  minimum_experience_years numeric(4, 1)
    check (minimum_experience_years is null or minimum_experience_years >= 0),
  salary_text text,
  posted_at timestamptz,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  inactive_at timestamptz,
  missing_sync_count integer not null default 0 check (missing_sync_count >= 0),
  dedupe_key text not null,
  content_hash text not null,
  parser_version text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (source_id, external_id)
);

create index job_postings_market_filter_idx
on public.job_postings (category, location_city, posted_at desc nulls last)
where inactive_at is null;

create index job_postings_company_idx
on public.job_postings (company_name, posted_at desc nulls last)
where inactive_at is null;

create table public.job_posting_skills (
  job_posting_id uuid not null references public.job_postings (id) on delete cascade,
  skill_slug text not null,
  skill_name text not null,
  skill_group text not null,
  requirement public.job_requirement_kind not null,
  evidence text not null,
  parser_version text not null,
  primary key (job_posting_id, skill_slug)
);

create table private.job_posting_payloads (
  job_posting_id uuid primary key references public.job_postings (id) on delete cascade,
  raw_payload jsonb not null,
  updated_at timestamptz not null default now(),
  check (jsonb_typeof(raw_payload) = 'object')
);

create index job_posting_skills_demand_idx
on public.job_posting_skills (skill_group, skill_slug);

alter table public.job_sources enable row level security;
alter table public.job_sync_runs enable row level security;
alter table public.job_sync_source_runs enable row level security;
alter table public.job_postings enable row level security;
alter table public.job_posting_skills enable row level security;
alter table private.job_posting_payloads enable row level security;

revoke all on table public.job_sources from anon, authenticated;
revoke all on table public.job_sync_runs from anon, authenticated;
revoke all on table public.job_sync_source_runs from anon, authenticated;
revoke all on table public.job_postings from anon, authenticated;
revoke all on table public.job_posting_skills from anon, authenticated;

grant select on table public.job_sources to authenticated;
grant select on table public.job_sync_runs to authenticated;
grant select on table public.job_sync_source_runs to authenticated;
grant select on table public.job_postings to authenticated;
grant select on table public.job_posting_skills to authenticated;

grant all on table public.job_sources to service_role;
grant all on table public.job_sync_runs to service_role;
grant all on table public.job_sync_source_runs to service_role;
grant all on table public.job_postings to service_role;
grant all on table public.job_posting_skills to service_role;
grant all on table private.job_posting_payloads to service_role;
grant usage, select on all sequences in schema public to service_role;

create policy "Approved users can read job sources"
on public.job_sources for select to authenticated
using ((select public.is_approved_user()));

create policy "Approved users can read job sync runs"
on public.job_sync_runs for select to authenticated
using ((select public.is_approved_user()));

create policy "Approved users can read job source sync runs"
on public.job_sync_source_runs for select to authenticated
using ((select public.is_approved_user()));

create policy "Approved users can read job postings"
on public.job_postings for select to authenticated
using ((select public.is_approved_user()));

create policy "Approved users can read job skills"
on public.job_posting_skills for select to authenticated
using ((select public.is_approved_user()));

insert into public.job_sources (id, name, source_type, source_url, requires_secret)
values
  ('jobicy-apac', 'Jobicy', 'jobicy', 'https://jobicy.com', false),
  ('remotive', 'Remotive', 'remotive', 'https://remotive.com', false),
  ('ashby-airwallex', 'Airwallex Careers', 'ashby', 'https://jobs.ashbyhq.com/airwallex', false),
  ('ashby-supabase', 'Supabase Careers', 'ashby', 'https://jobs.ashbyhq.com/supabase', false),
  ('lever-binance', 'Binance Careers', 'lever', 'https://jobs.lever.co/binance', false),
  ('jooble-vn', 'Jooble', 'jooble', 'https://jooble.org', true);

comment on table public.job_postings is
  'Normalized job-market records shared by approved Hub William users. Full provider payloads stay in the private schema.';

comment on column public.job_postings.seniority_source is
  'Whether seniority came directly from a title/source, was inferred from experience wording, or could not be determined.';
